
#Workspace for Project 2

```{r}
library(readr)
library(tidyverse)
library(tidycensus)
library(flextable)
library(sf)
library(tigris)
library(tmap)
library(RColorBrewer)
```


Initial mapping of datasets independently
```{r}
ggplot() +
  geom_sf(data = PAD_CA_sf, aes(fill = mang_level)) +
  labs(fill = "Management Level") +
  theme_void()

ggplot() +
  geom_sf(data = fires_sf, aes(fill = discover_yr)) +
  labs(fill = "Year") +
  theme_void()

ggplot() +
  geom_sf(data = fires_sf, aes(fill = factor(discover_yr))) +
  labs(fill = "Year") +
  scale_fill_manual(values = rainbow(length(unique(fires_sf$discover_yr)))) +
  theme_void()
```

```{r}

```



Animated Plot of Wildfires each year (no county/mangament boundaries)
```{r}
library(countdown)
library(gt)
library(readxl)
library(gganimate)
library(gifski)
library(knitr)
library(kableExtra)
library(transformr)


p <- ggplot() +
  geom_sf(data = fires_sf, aes(fill = factor(discover_yr))) +
  labs(fill = "Year") +
  theme_void() 

p + transition_states(discover_yr, transition_length = 1, state_length = 1)

animate(p)

```


