

```{r}
library(readr)
library(tidyverse)
library(tidycensus)
library(flextable)
library(sf)
library(tigris)
library(tmap)
library(RColorBrewer)
```

Fire Dataset Cleanup:
- removing unneccesary variables
- renaming variables
```{r}
fires <- read_csv("~/Rstudio/DataScience/project-02-kiana/Data/fires.csv", 
                  col_types = cols(COMMENT = col_skip(),
                                   last_edited_user = col_skip(),
                                   last_edited_date = col_skip(),
                                   created_user = col_skip(),
                                   created_date_2 = col_skip(),
                                   created_date = col_skip(),
                                   created_by_name = col_skip(),
                                   modified_date = col_skip(),
                                   modify_by_name = col_skip(),
                                   wildland_fire_perimeter_comments = col_skip()
                  ))


#POI: point of orgin, UI: unit identifier, UC = unit code
fires <- fires %>% 
  rename(POI_Jurisdictional_UI = point_of_origin_jurisdictional_unit_identifier,
         POI_Protecting_UI = point_of_origin_protecting_unit_identifier,
         reporting_UI = reported_unit_identifier,
         incident_num = fire_incident_number,
         name = incident_name,
         cause_gen = incident_general_cause_name,
         admin_UC = administrative_unit_code,
         uniquie_fireID = unique_fire_identifier,
         discover_yr = fire_discovered_calendar_year,
         discover_date = fire_discovered_date,
         controlled_date = fire_control_date,
         acres_total = total_reported_acres
         )


```


PAD_CA Dataset Cleanup:
- removing unneeded variables
- renaming variables
```{r}
PAD_CA <- read_csv("~/Rstudio/DataScience/project-02-kiana/Data/PAD_CA.csv", 
                  col_types = cols(FeatClass = col_skip(),
                                   Category = col_skip(),
                                   Loc_Own = col_skip(),
                                   Loc_Mang = col_skip(),
                                   Own_Type = col_skip(),
                                   Own_Name = col_skip(),
                                   EHoldTyp = col_skip(),
                                   EsmtHldr = col_skip(),
                                   Comments = col_skip(),
                                   Date_Est = col_skip(),
                                   IUCNCtDt = col_skip(),
                                   IUCN_Cat = col_skip(),
                                   IUCNCtSrc = col_skip(),
                                   Access_Src = col_skip(),
                                   Access_Dt = col_skip(),
                                   Loc_Ds = col_skip(),
                                   Loc_Nm = col_skip(),
                                   Src_Date = col_skip(),
                                   Unit_Nm = col_skip(),
                                   Pub_Access = col_skip(),
                                   GAP_Sts = col_skip(),
                                   GAPCdSrc = col_skip(),
                                   GAPCdDt = col_skip()
                                   ))

PAD_CA <- PAD_CA %>% 
  rename(mang_level = Mang_Type,
         mang_name = Mang_Name,
         designation = Des_Tp
         )

```

Making Spatial
-reducing management types down to American Indian Lands, Federal, Local Government, and State
```{r}
fires_sf <- fires %>%
  filter(!is.na(WKT)) %>%
  st_as_sf(wkt = "WKT")

PAD_CA_sf <- PAD_CA %>%
  filter(!is.na(WKT)) %>%
  filter(mang_level != "Unknown") %>% 
  filter(mang_level != "Private") %>% 
  filter(mang_level != "Non-Governmental Organization") %>% 
  mutate(mang_level = case_when(
    mang_level == "Regional Agency Special District" ~ "Local Government",
    mang_level == "Joint" ~ "Local Government",
    TRUE ~ mang_level
  )) %>% 
  st_as_sf(wkt = "WKT") 


```


Merging Datasets:
fires and land management
```{r}
fire_location <- read_csv("~/Rstudio/DataScience/project-02-kiana/Data/fire_location_data.csv")
```


Merging Datasets:
fires and oregon counties
```{r}
library(tidyverse)
library(tidycensus)

library(sf)
library(tigris)
ca_sf <- counties(state = "CA", cb = TRUE)


fires_sf <- st_as_sf(fires_sf, wkt = "WKT")
ca_sf <- st_as_sf(ca_sf, wkt = "geometry")

st_crs(fires_sf) <- st_crs(ca_sf)
fires_sf <- st_make_valid(fires_sf)

fires_county <- st_intersection(fires_sf, ca_sf)
fires_county$NAME <- fires_county$NAME

#removing unnecessary columns
fires_county_cleanup <- c("POI_Jurisdictional_UI", 
                          "POI_Protecting_UI", 
                          "reporting_UI",
                          "fire_discovered_date_estimated_flag",
                          "fire_control_date_estimated_flag",
                          "collection_method",
                          "CREATE_DAT",
                          "CREATE_BY",
                          "MODIFY_DAT",
                          "MODIFY_BY",
                          "created_us",
                          "created_da",
                          "last_edite",
                          "last_edi_1",
                          "administrative_state_code",
                          "complex_name",
                          "fire_code",
                          "incident_num",
                          "irwin_identifier",
                          "admin_UC",
                          "uniquie_fireID",
                          "FIRE_DSCVR",
                          "FIRE_DSC_1",
                          "FIRE_DSC_2",
                          "FIRE_CNTRL",
                          "FIRE_CNT_1",
                          "FIRE_CAUSE",
                          "TOTAL_RPT_",
                          "CMPLX_NM",
                          "COUNTYFP",
                          "COUNTYNS",
                          "STATEFP",
                          "IRWIN_ID",
                          "ADM_UNIT_C",
                          "ADMIN_ST",
                          "UNQE_FIRE_",
                          "STUSPS",
                          "LSAD",
                          "STATE_NAME"
                          ) 
fires_county <- fires_county %>%
  select(-one_of(fires_county_cleanup))

#renaming
fires_county <- fires_county %>% 
  rename(fire_name = name,
         cause = cause_gen,
         county_name = NAME,
         county_name_full = NAMELSAD
         )

#fire counts by county stats
fire_counts <- fires_county %>%
  group_by(county_name) %>%
  summarize(fire_count = n()) %>%
  mutate(percentage = (fire_count / sum(fire_count)) * 100)

```


